server:
  port: 8002

spring:
  application:
    name: app-server-2

eureka:
  instance:
#    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ip-address}:8761/eureka/
    # 心跳检测
    healthcheck:
      enabled: true